## Laptop Price prediction model

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df = pd.read_csv("laptopPrice.csv")
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [3]:
df.dropna(inplace = True)
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [4]:
df.drop_duplicates(inplace = True)
df.duplicated().sum()

0

In [5]:
independent_columns = ["graphic_card_gb","brand", "os", "os_bit", "weight", "warranty", "msoffice", "rating", "Number of Ratings", "Number of Reviews", "ram_gb", "ssd", "hdd"]
df.drop(columns=independent_columns, inplace=True)
df

,processor_brand,processor_name,processor_gnrtn,ram_type,Touchscreen,Price
0,Intel,Core i3,10th,DDR4,No,34649
1,Intel,Core i3,10th,DDR4,No,38999
2,Intel,Core i3,10th,DDR4,No,39999
3,Intel,Core i5,10th,DDR4,No,69990
4,Intel,Celeron Dual,Not Available,DDR4,No,26990
...,...,...,...,...,...,...
818,AMD,Ryzen 9,Not Available,DDR4,No,135990
819,AMD,Ryzen 9,Not Available,DDR4,No,144990
820,AMD,Ryzen 9,Not Available,DDR4,No,149990
821,AMD,Ryzen 9,Not Available,DDR4,No,142990
822,AMD,Ryzen 5,10th,DDR4,No,57490

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [7]:
output = encoder.fit_transform(df['processor_brand'])
df["processor_brand"] = output
df

,processor_brand,processor_name,processor_gnrtn,ram_type,Touchscreen,Price
0,1,Core i3,10th,DDR4,No,34649
1,1,Core i3,10th,DDR4,No,38999
2,1,Core i3,10th,DDR4,No,39999
3,1,Core i5,10th,DDR4,No,69990
4,1,Celeron Dual,Not Available,DDR4,No,26990
...,...,...,...,...,...,...
818,0,Ryzen 9,Not Available,DDR4,No,135990
819,0,Ryzen 9,Not Available,DDR4,No,144990
820,0,Ryzen 9,Not Available,DDR4,No,149990
821,0,Ryzen 9,Not Available,DDR4,No,142990
822,0,Ryzen 5,10th,DDR4,No,57490

In [8]:
output = encoder.fit_transform(df['processor_name'])
df["processor_name"] = output
df

,processor_brand,processor_name,processor_gnrtn,ram_type,Touchscreen,Price
0,1,1,10th,DDR4,No,34649
1,1,1,10th,DDR4,No,38999
2,1,1,10th,DDR4,No,39999
3,1,2,10th,DDR4,No,69990
4,1,0,Not Available,DDR4,No,26990
...,...,...,...,...,...,...
818,0,10,Not Available,DDR4,No,135990
819,0,10,Not Available,DDR4,No,144990
820,0,10,Not Available,DDR4,No,149990
821,0,10,Not Available,DDR4,No,142990
822,0,8,10th,DDR4,No,57490

In [9]:
output = encoder.fit_transform(df['processor_gnrtn'])
df["processor_gnrtn"] = output
df

,processor_brand,processor_name,processor_gnrtn,ram_type,Touchscreen,Price
0,1,1,0,DDR4,No,34649
1,1,1,0,DDR4,No,38999
2,1,1,0,DDR4,No,39999
3,1,2,0,DDR4,No,69990
4,1,0,7,DDR4,No,26990
...,...,...,...,...,...,...
818,0,10,7,DDR4,No,135990
819,0,10,7,DDR4,No,144990
820,0,10,7,DDR4,No,149990
821,0,10,7,DDR4,No,142990
822,0,8,0,DDR4,No,57490

In [10]:
output = encoder.fit_transform(df['ram_type'])
df["ram_type"] = output
df

,processor_brand,processor_name,processor_gnrtn,ram_type,Touchscreen,Price
0,1,1,0,1,No,34649
1,1,1,0,1,No,38999
2,1,1,0,1,No,39999
3,1,2,0,1,No,69990
4,1,0,7,1,No,26990
...,...,...,...,...,...,...
818,0,10,7,1,No,135990
819,0,10,7,1,No,144990
820,0,10,7,1,No,149990
821,0,10,7,1,No,142990
822,0,8,0,1,No,57490

In [11]:
output = encoder.fit_transform(df['Touchscreen'])
df["Touchscreen"] = output
df

,processor_brand,processor_name,processor_gnrtn,ram_type,Touchscreen,Price
0,1,1,0,1,0,34649
1,1,1,0,1,0,38999
2,1,1,0,1,0,39999
3,1,2,0,1,0,69990
4,1,0,7,1,0,26990
...,...,...,...,...,...,...
818,0,10,7,1,0,135990
819,0,10,7,1,0,144990
820,0,10,7,1,0,149990
821,0,10,7,1,0,142990
822,0,8,0,1,0,57490

In [12]:

from sklearn.model_selection import train_test_split
x = df.drop(columns=["Price"])
y = df[['Price']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [13]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [17]:
lr.score(x_train, y_train) * 100

36.55179232895067

In [18]:
lr.score(x_test, y_test) * 100

35.25927950380036

In [19]:
pred = lr.predict(x_test)

In [20]:
y_test['pred'] = pred.ravel()
y_test

      Price           pred
196   50990   44964.726930
299   72990   94650.573173
171   41490   59377.458428
537  144690   90301.317882
551  129990   85141.694552
..      ...            ...
368  114990  110254.075178
361  126000   90442.890160
446   57990   69679.764825
767  106990   84031.791137
529  110999   85141.694552

[161 rows x 2 columns]